# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

refit_LA_ADMM_export <- function(it_out, it_in, S, A, Atilde, A_for_gamma, A_for_B, C, C_for_D, rho, omP, init_om, init_u1, init_u2, init_u3, init_gam, init_u4, init_u5) {
    .Call(`_taglasso_refit_LA_ADMM_export`, it_out, it_in, S, A, Atilde, A_for_gamma, A_for_B, C, C_for_D, rho, omP, init_om, init_u1, init_u2, init_u3, init_gam, init_u4, init_u5)
}

LA_ADMM_taglasso_export <- function(it_out, it_in, S, A, Atilde, A_for_gamma, A_for_B, C, C_for_D, lambda1, lambda2, rho, pendiag, init_om, init_u1, init_u2, init_u3, init_gam, init_u4, init_u5) {
    .Call(`_taglasso_LA_ADMM_taglasso_export`, it_out, it_in, S, A, Atilde, A_for_gamma, A_for_B, C, C_for_D, lambda1, lambda2, rho, pendiag, init_om, init_u1, init_u2, init_u3, init_gam, init_u4, init_u5)
}

determine_dfs <- function(A, tol = 1e-06) {
    .Call(`_taglasso_determine_dfs`, A, tol)
}

matrix_unique_rows <- function(A) {
    .Call(`_taglasso_matrix_unique_rows`, A)
}

ADMM_taglasso_cv_parallel <- function(fold_vector, lambda1_vector, lambda1_index_vector, lambda2_vector, lambda2_index_vector, Sin, Sout, fold, A, lambda1, lambda2, rho, pendiag, it_out, it_in, it_out_refit, it_in_refit, do_parallel, nc) {
    .Call(`_taglasso_ADMM_taglasso_cv_parallel`, fold_vector, lambda1_vector, lambda1_index_vector, lambda2_vector, lambda2_index_vector, Sin, Sout, fold, A, lambda1, lambda2, rho, pendiag, it_out, it_in, it_out_refit, it_in_refit, do_parallel, nc)
}

